export type TabType =
  | "pos"
  | "cola"
  | "cierre"
  | "egresos"
  | "importer"
  | "liquidaciones"
  | "tarifario"
  | "admin"
  | "alquileres"
  | "comprobantes"
  | "estadisticas"
  | "reportes"
  | "farmacia"
  | "inventario_general";
